### ISSUE TITLE
Question: when can we expect next release?

### ISSUE THREAD

**Issue by ngaurav** [Daemonite/material#100]
The back-filling-bootstrap-4 branch is ahead of master by almost 100 commits now. I think it will be better if the templates directory in the branch gets some attention. Or else a dev pre-release will be do the job. I am excited to know how to use the new elements.

**Comment by banago** [comment]
@sesemaya same question here. I want to start using this for a project, but I don't want to re-do it when switching to bootstrap 4. Is there any plans for merging into master?

**Comment by modius** [comment]
We've been in a bit of a holding pattern in the hope that the Bootstrap project move a little faster.  There's no reason you can't work with the head of the `back-filling-bootstrap-4` branch; we have ourselves for several projects.

**Comment by sesemaya** [comment]
Closing as `backfilling-bootstrap-4` has been merged into `master`.

We are currently working on `backfilling-bootstrap-4.0.0-alpha.6`.

As Bootstrap announced that alpha.6 would be the last alpha before the more stable beta version, we will be looking into adding bug fixes and enriching our material ui library rather than backfilling Bootstrap once it reaches its beta stage.
