### ISSUE TITLE
CSS modal header class name

### ISSUE THREAD

**Issue by javaguru-ch** [Daemonite/material#103]
On the [bootstrap page](http://getbootstrap.com/javascript/#modals) the CSS class for the modal header section is called "modal-header". However, in daemonite-material it is called "modal-heading". 
Why is this different from the bootstrap class name?

**Comment by sesemaya** [comment]
this has been fixed in [the `back-filling-bootstrap-4` branch](https://github.com/Daemonite/material/tree/back-filling-bootstrap-4) which honours all bootstrap class names

the idea of the new branch is if you replace the `bootstrap.css` on the bootstrap documentation site with the `material.css`, everything will still work with a material look applied to all the components (some additional material-only components will also be available)

however, this new branch is still work in progress, but we are looking to have an alpha version ready in the near future

**Comment by sesemaya** [comment]
All Bootstrap CSS selectors are supported since https://github.com/Daemonite/material/releases/tag/v4.0.0-alpha.0
