### ISSUE TITLE
Files ?

### ISSUE THREAD

**Issue by Touficbatache** [Daemonite/material#110]
Where are all the files

**Comment by sesemaya** [comment]
Hi @Touficbatache, the previous `master` has been moved to the `maintenance` branch.

Sorry for the lack of communication and documentation, but it's been in the works for a while, we've had to keep it under wraps because of the excruciatingly slow release of the Bootstrap 4 Alpha. As the Bootstrap 4 project is starting to pick up momentum, we thought it was a good time to put our best foot forward.

We've changed the approach to a complete "drop-in" option for the bootstrap.css -- you can literally swap the CSS on the Bootstrap 4 documentation site for a complete Material makeover.
