### ISSUE TITLE
Doesn't work with Angular CLI project

### ISSUE THREAD

**Issue by martinsiden** [Daemonite/material#114]
Hello!

Thanks for all you hard work on this. 

I'm trying to use your CSS in a brand new Angular 2 project, but am currently running into some problems. 

I have used Angular CLI to setup a brand new project, and the only thing changed after that is adding the path towards your CSS in the `angular-cli.json` file to make it global:

`"styles": [
  "../node_modules/daemonite-material/css/material.css",
  "styles.css"
],`

I have tried both the minified version and the normal stylesheet, but both produce:

`ERROR in ./~/css-loader!./~/postcss-loader!./src/styles.css
Module not found: Error: Can't resolve './' in 'C:\Users\Martin\Desktop\my-project\src'
 @ ./~/css-loader!./~/postcss-loader!./src/styles.css 6:244670-244683 6:244715-244728
 @ ./src/styles.css
 @ multi styles`

This method works just fine with the CSS files from Bootstrap 4 like this:

`"styles": [
   "../node_modules/bootstrap/dist/css/bootstrap.css",
   "styles.css"
],` 

I guess there's something in your CSS that the webpack CSS loader can't handle? Or am I doing something wrong?

**Comment by sesemaya** [comment]
Hi @martinsiden 

This is probably due to the following rules in `material.css`:
```
.waves-circle > .waves-wrap {
  -webkit-mask: url();
                mask: url();
}
```
A temporary fix is to change `url()` to `none` or to remove the entire rules.

Angular CLI or Webpack may also have some options/settings available to bypass things like these.

I'll review css for waves in the next release, and hopefully get it fixed for good.

**Comment by ssijak** [comment]
this still does not work
