### ISSUE TITLE
btn-outline is misleading

### ISSUE THREAD

**Issue by poldiwa** [Daemonite/material#146]
I don't know what would be the effect to the framework but I think `.btn-outline` should be `.btn-flat`, and maybe let's keep the .btn-outline used by bs

**Comment by sesemaya** [comment]
Agree that it is probably better to have a `.btn-flat` selector (and documented in Material section of the doc site), but not sure what to do with `.btn-outline` since Material Design does not specify anything remotely similar. 

I think for now I will keep `.btn-outline` as it is now and `.btn-flat` will behave in the same way.
