### ISSUE TITLE
noborder for list-group-item

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#153]
Hi,
sorry to disturb you again.
I try to set a border: 0 for list-group-items but these borders won't go away !
My tweaks work for Bootstrap 4 beta 2 but not on Daemonite.
Any idea ?

By the way, I'm skinning Select2, Clockpicker and DateTimePicker to create an Extra folder for Daemonite.
Thank you for everything.

**Comment by sesemaya** [comment]
The "`border`" of an `.list-group-item` in Material is actually `box-shadow`, this is why your fix does not work here.

You can try to use `box-shadow: none;` instead of `border: 0;`.

Alternatively, you can try set `.list-group-flush` on `.list-group`, which reverts `.list-group-item`s to use `border` instead of `box-shadow` (example [here](http://daemonite.github.io/material/docs/4.0/components/card/#list-groups)), and then you can apply `border: 0;` on `.list-group-item`s.

**Comment by djibe** [comment]
You are the best, as always ! Thx a lot
