### ISSUE TITLE
py-no

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#157]
Hi guys,
in your documentation, for Material tables, you use the py-no class.
This py-no class is not bootstrap standard.
I see in your CSS it is the same as py-0.

What is the purpose of this class ?
Thanks for your help.

**Comment by sesemaya** [comment]
Hi @djibe, we implemented our own margin/padding utility classes in a very early version of Material which was before Bootstrap 4 that introduces its own utility classes came out. We used syntax `no`, `xs`, `sm`, etc. instead of `0`, `1`, `2`, etc. and apparently it has been kept in the code. We will look to clean it up before the final v4 release.

**Comment by djibe** [comment]
Thank you for everything. As always.

I was thinking about tables improvement, what do you think of this class ?
.table-hover tbody tr {
	transition: all .3s;
}
It makes table-hover tables much more fluid isn't it ?
