### ISSUE TITLE
Label on left of Switch

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#158]
Hi, sorry to bother you again.

How can we set the label of a Switch on the left ?
It seems this control is flex, so I tried "order" CSS properties for flexboxes but it didn't work.

Thanks again

**Comment by sesemaya** [comment]
Hi @djibe 

The switch is `absolute` positioned to the left of the `.custom-switch`, so flex utility classes won't change its positioning. 

In order to achieve what you asked, you may need some custom CSS:
1. Replace `.custom-switch`'s `padding-left` with `padding-right`
2. Adjust `.custom-control-indicator`'s position from `left: 0;` to `right: 0; left: auto'`

**Comment by djibe** [comment]
Thank you so much. As always
