### ISSUE TITLE
typography-display-4

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#162]
Hi Maya,
why do you use "typography-display-4" class instead of BS4 standard "display-4" ?
Thanks for all.

**Comment by sesemaya** [comment]
This is also leftover from our own utility classes before BS4 introduced its typography utility classes, but BS4 standard typography classes such as `display-4` are also supported now.

I intend to keep all the `typography-` classes because they cover a bit more than BS4's 4 `display-` classes.

For all the supported `typography-` classes, please refer to: https://material.io/guidelines/style/typography.html#typography-styles for now. I may need to set up a separate doc page under `Material` to document these.

**Comment by djibe** [comment]
Thanks.

BS4 final is here ;-)

**Comment by sesemaya** [comment]
Details about Material typography are added to the latest documentation.
