### ISSUE TITLE
Submit for Search field with floating label + input-group icon, form validation

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#168]
I did the following fiddle cause I feel it's missing in Daemonite
https://jsfiddle.net/djibe89/13tzf7L4/

I also did a fiddle for using form validation with your Daemonite, it works perfectly with Parsley
https://jsfiddle.net/djibe89/9yoow8z3/

**Comment by sesemaya** [comment]
fb8c33b fixed a couple of issues with having `.floating-label` or `.textfield-boxes` in `.input-group`.

Working on the icon part now, but my idea is to have icons come after form controls in HTML and then move them in front using `order` so we can change the colour of the icons without JavaScript. 

May need to create a new class though (maybe `.input-group-icon`), since this isn't a default Bootstrap behaviour, I guess it would be ok then.

**Comment by djibe** [comment]
You rock. As usual

**Comment by djibe** [comment]
Thank you so much for this perfect release
