### ISSUE TITLE
Elevation parameters

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#175]
Hi Maya,
I was wondering the source of your cards box-shadows.

I found these ones, supported by Google for the Web. What do you think ?

https://material-components-web.appspot.com/elevation.html

Thanks a lot, sorry to bother you all the time.

**Comment by sesemaya** [comment]
It seems like Bootstrap is adding `box-shadow` utilities: https://github.com/twbs/bootstrap/pull/25758, so we will add something compatible with Bootstrap and then extend it to include support for all the extra Material values. This should be an easy one since all the shadows have already been defined in `assets/scss/variables/_elevation-shadow.scss`.

**Comment by djibe** [comment]
Thanks for advice.

**Comment by sesemaya** [comment]
Box shadow utility classes added in `v4.1.0`
