### ISSUE TITLE
Swipe Navigation drawer

### ISSUE THREAD

**Issue by agnichakra** [Daemonite/material#235]
I think Material is the best framework I have ever used. It's true.  My only requirement is can the navigation made mobile friendly. Touch swipe ie it can be pulled and pushed in the mobile? Thanks in advance.
![Navigation-Drawer-In-Android](https://user-images.githubusercontent.com/36500522/66719130-37375400-ee09-11e9-88a9-c9ab2e73fc29.gif)

**Comment by sesemaya** [comment]
Hi @agnichakra,

Unfortunately, this would not be part of this project as this is more of an enhaced feature rather than a more generic feature (e.g. hamburger menu). You can achieve this by using some custom JavaScript or third pary library for detecting swipes and then trigger `.navdrawer('hide')` or `.navdrawer('show')` accordingly.
