### ISSUE TITLE
Elevation & shadows

### ISSUE THREAD

**Issue by obsidienne** [Daemonite/material#45]
[elevation & shadows](http://www.google.com/design/spec/what-is-material/elevation-shadows.html) describes precisely z-index and shadows.

I will do a pull request, but I need some guidance on how to do that. 
Using placeholder ? mixins ?

**Comment by sesemaya** [comment]
hi @obsidienne 

the elevation spec seems to be for android apps. directly implementing all the z-index values may not work on web pages though...

shadows may be much easier and more straightforward to implement. probably as variables.

**Comment by surajwebworld** [comment]
can u make it swipe menu

**Comment by phamhathanh** [comment]
@sesemaya I think the elevation and shadow are quite strongly related. Without elevation there won't be stuffs like [this](http://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3UW5QQ010bm0tZFk/whatismaterial_3d_elevation_shadow3.png).

Static shadow is ok, but I guess it won't be as "material-ish".

**Comment by sesemaya** [comment]
V4 has defined all `elevation and shadow` as variables in [`_variable-elevation-shadow.scss`](https://github.com/Daemonite/material/blob/master/assets/sass/variables/_elevation-shadow.scss). They are then mapped to individual components in [`_variable-material.scss`](https://github.com/Daemonite/material/blob/master/assets/sass/variables/_elevation-shadow.scss).

However, the values of `elevation` are 10 X the values in Material Design Guidelines because `z-index` ranging only from 1 to 24 does not provide enough flexibility for web design/development.
