### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by Cadiducho** [Daemonite/material#53]
Is there any way to create pagination with Material? Some like 
![image](https://cloud.githubusercontent.com/assets/3594924/8520750/9be71426-23dd-11e5-9b34-eb7bc7387bb5.png)

**Comment by sesemaya** [comment]
hi @Cadiducho this is a hard one because google material design guideline doesn't specify styles for pagination or pagination like elements. 

at this moment you may need to use a combination of `.nav .nav-justified` and `.tile` to work out something as a pagination. an example can be found at the bottom of this page: http://daemonite.github.io/material/ui-nav

**Comment by modius** [comment]
![material-pagination](https://cloud.githubusercontent.com/assets/20687/10126348/c1d2118a-65d3-11e5-9261-225be5b54cdb.jpg)

**Example using `.nav-list`**
```html
<ul class="nav nav-list">
	<li>
		<a class="tile waves-attach waves-effect" href="javascript:void(0)">Home</a>
	</li>
	<li>
		<a class="tile waves-attach waves-effect" href="javascript:void(0)">Element</a>
	</li>
	<li>
		<a class="tile waves-attach waves-effect" href="javascript:void(0)">Theme</a>
	</li>
</ul>
```

**Example using `.nav-justified`**
```html
<ul class="nav nav-justified">
	<li>
		<a class="tile waves-attach waves-effect" href="javascript:void(0)">Home</a>
	</li>
	<li>
		<a class="tile waves-attach waves-effect" href="javascript:void(0)">Element</a>
	</li>
	<li>
		<a class="tile waves-attach waves-effect" href="javascript:void(0)">Theme</a>
	</li>
</ul>
```
