### ISSUE TITLE
separated bootstrap and material base css

### ISSUE THREAD

**Issue by adiramardiani** [Daemonite/material#83]
I think is more modular with this structure :

```html
<link href="dist/css/bootstrap.css">
<link href="dist/css/material-design.css">

<script src="dist/js/bootstrap.js"></script>
<script src="dist/js/material-design.js"></script>
```
For now it's to hard for make extensible with bootstrap

**Comment by cansanet** [comment]
I think the same also, it would be nicer this way. Than we can extend elements more quickly.

**Comment by adiramardiani** [comment]
For new version, I think this time to separated bootstrap and material base css

**Comment by sesemaya** [comment]
JavaScript has been separated in the new version `v4.0.0-alpha.1` (current `master`). 

Regarding CSS, I intended to do the same but found that separating `bootstrap.css` from `material.css` isn't a practical solution. 

For example, `bootstrap.css` has its own grid system with breakpoints that are different to the breakpoints defined in [Material Design Guidelines](https://material.google.com/layout/responsive-ui.html#responsive-ui-breakpoints), so for this module to work, the `material.css` needs to
1) stop the grid system triggering new layout at Bootstrap breakpoints:
```
/* Bootstrap md breakpoint is 768px */
@media (min-width: 768px) {
    .col-md-* {
        float: none;
        width: auto;
        ...
    }
}
```
2) set new breakpoints for `md` according to Material Design Guidelines:
```
/* Material md breakpoint is 960px */
@media (min-width: 960px) {
    .col-md-* {
        float: left;
        width: ...%;
        ...
    }
}
```

Again, for `material.css` to style a component like `.btn` in this module, it first needs to reset quite a lot of styles it will inherit from `.btn` in `bootstrap.css` and then adds new styles on top of it.

The same will basically apply to every single Bootstrap component because `material.css` is basically restyling them completely. 

Therefore, although you have `bootstrap.css` and `material.css` separately in the end, the `bootstrap.css` will be basically useless as the majority of it will be overridden by `material.css`. Meanwhile, the size of `material.css` can potentially be doubled as maybe half of it will be resetting styles in `bootstrap.css`.
