### ISSUE TITLE
Bootstrap 4 align

### ISSUE THREAD

**Issue by Delagen** [Daemonite/material#95]
I see that variables in SCSS contains names that different in bootstrap 4, since it use SASS for build project. So I would like to see that is project fully compatible with 4 version

**Comment by modius** [comment]
Are you referring to the `master` branch or the `back-filling-bootstrap-4` branch currently under development?

https://github.com/Daemonite/material/tree/back-filling-bootstrap-4

**Comment by sesemaya** [comment]
The current `master` is now fully compatible with Bootstrap 4. All Bootstrap 4 CSS selectors and HTML markup are supported. 

However, due to the significant differences between Bootstrap and Material Design Guidelines, this project needs more far variables than Bootstrap 4 while some are not needed at all.
